# GitHub Pages configuration
title: "Политика конфиденциальности Binom AI Signals"
description: "Политика конфиденциальности Android-приложения Binom AI Signals"
theme: jekyll-theme-minimal
lang: ru-RU
